### ISSUE TITLE
lite.properties (No such file or directory) 

### ISSUE THREAD

**Issue by gzp1124** [YouROK/M3U8Loader#4]
R.T.

**Comment by YouROK** [comment]
Make a file lite.properties in root of project and add to
storePassword=yourPassword
keyPassword=yourPassword
keyAlias=yourAlias
storeFile=path/to/key

**Comment by xingyunjohn1** [comment]
`/home/runner/work/android_builder/android_builder/project/convert.properties (No such file or directory)`
